name: CI Workflow

on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with pytest
        run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing

  code_quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Add your SonarQube token in GitHub secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://your-sonarqube-server.com \
            -Dsonar.login=$SONAR_TOKEN

  security_scan:
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          apt-get update && apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.39.0_Linux-64bit.deb
          dpkg -i trivy_0.39.0_Linux-64bit.deb

      - name: Run Trivy Vulnerability Scan
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL your_image_name:latest
